// this file was generated by serverless-auto-swagger
            module.exports = {
  "swagger": "2.0",
  "info": {
    "title": "product",
    "version": "1"
  },
  "paths": {
    "/products": {
      "get": {
        "summary": "getProductsList",
        "description": "",
        "operationId": "getProductsList.get.products",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/product/{id}": {
      "get": {
        "summary": "getProductItem",
        "description": "",
        "operationId": "getProductItem.get.product/{id}",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    }
  },
  "definitions": {
    "Car": {
      "properties": {
        "id": {
          "title": "Car.id",
          "type": "string"
        },
        "brand": {
          "title": "Car.brand",
          "type": "string"
        },
        "name": {
          "title": "Car.name",
          "type": "string"
        },
        "price": {
          "title": "Car.price",
          "type": "number"
        },
        "description": {
          "title": "Car.description",
          "type": "string"
        }
      },
      "required": [
        "id",
        "brand",
        "name",
        "price",
        "description"
      ],
      "additionalProperties": false,
      "title": "Car",
      "type": "object"
    }
  },
  "securityDefinitions": {},
  "host": "q11j9jr031.execute-api.us-east-1.amazonaws.com/dev"
};